### PR TITLE
Compile using g++, to automatically link against the correct libstdc++.

### PR DESCRIPTION
**Pull request by OscarL**
Fixes builds on Haiku x86_gcc2.

### CODE REVIEW

**Comment by steffenyount** [comment]
Looks good to me, Merged.

**Comment by steffenyount** [comment]
@OscarL - Thank you for this set of PRs. Do you have anymore pending?

Should I cut a new release version to include these changes?

**Comment by steffenyount** [comment]
> @steffenyount: no problem, thanks for DrumCircle! Used it for the first time today... quite fun!

Glad to hear it :-)

Does the app's icon show up now?

> 
> No pending PRs for my part. Albeit... perhaps one cleaning up a bit the ".gitignore" file and adding "DrumCircle" to it should be in order?

If you want to submit that PR I'll merge it. If I recall correctly, I just took the GitHub default for the current ".gitignore" file's contents.

After that, I'll cut another point release.

I'd like to say thanks in the updated release notes, what name should I use for you?

Thanks,
-Steffen

**Comment by steffenyount** [comment]
I made a new release: DrumCircle-1.0.5

Do you know what needs to be updated on the HaikuPorts side? Could I ask you to drive those changes?

Thanks again.

**Comment by OscarL** [comment]
I'll do a PR for the recipe update to 1.0.5, and we'll wait for someone to merge it (or provide feedback on my poor attempts at least :-D)

**Comment by steffenyount** [comment]
Thank you!

**Comment by OscarL** [comment]
> Does the app's icon show up now?

Forgot to reply to this: Yes, it does thanks to @augiedoggie's commit (which was merged in #5).

**Pull request merged**
