### PR TITLE
prepare for haikuports packaging

### PR DESCRIPTION
**Pull request by davidkaroly**
* add "make install"
* add variables for install destination directories
* load dots from datadir (default to Stuff)
* load/save profiles to settingsdir (default to Profiles)

### CODE REVIEW

**Comment by davidkaroly** [comment]
I'm not entirely sure about the Profiles related code in DrumCircleApp::ReadyToRun() does it do some kind of pre-loading of profile data? Is it really needed?

**Comment by davidkaroly** [comment]
ehh for get about my previous comment first I should do some code study before asking obvious questions :stuck_out_tongue_winking_eye: 
I'll just update DrumCircleApp::ReadyToRun()

**Comment by steffenyount** [comment]
merged

**Comment by davidkaroly** [comment]
> Is the app still able to find the profile files that live under 'Profiles/' in its home dir after this change?
> 
> I assume yes? (Did you see this working on your machine?)

I did the following test
* build manually with `make`, no extra command line arguments - the resulting binary looks for stuff and profiles relatively from the current working directory
* build from recipe with haikuporter, the absolute pathnames are built into the binary

**Comment by steffenyount** [comment]
ok, great!

**Pull request merged**
